resilience4j:
  ratelimiter:
    instances:
      deductLimiter:
        limitForPeriod: 200
        limitRefreshPeriod: 1s
        timeoutDuration: 0
  circuitbreaker:
    instances:
      deductBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        recordExceptions:
          - java.lang.Exception
        ignoreExceptions:
          - com.utgaming.testconcurrency.common.BusinessException
server:
  servlet:
    context-path: /api
  port: 90
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/testConcurrency?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 242859
  shardingsphere:
    database-name: testConcurrency
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://mysql:3306/testConcurrency?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&useInformationSchema=true&nullCatalogMeansCurrent=true
        username: root
        password: 242859
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://mysql-slave:3306/testConcurrency?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&useInformationSchema=true&nullCatalogMeansCurrent=true
        username: root
        password: 242859
    rules:
      readwrite-splitting:
        data-sources:
          rw_ds:
            type: Static
            props:
              write-data-source-name: master
              read-data-source-names: slave
    props:
      sql-show: true
      check-table-metadata-enabled: false
  data:
    # redis配置
    redis:
      # Redis数据库索引（默认为0）
      database: 1
      # Redis服务器连接密码（默认为空）
      password: 242859

      sentinel:
        master: mymaster
        nodes:
          - 127.0.0.1:26379
          - 127.0.0.1:26380
          - 127.0.0.1:26381
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        min.insync.replicas: 2
    consumer:
      group-id: stock-writeback-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.utgaming.testconcurrency.common"
        spring.json.value.default.type: com.utgaming.testconcurrency.common.StockDeductMessage
#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: INFO
mybatis:
  mapper-locations: classpath:mapper/*.xml


app:
  sharding:
    enabled: false
  cache:
    enabled: true
  stock:
    async:
      enabled: false
    kafka:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
